version: "3.8"

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '12345678'
      POSTGRES_DB: 'shorturl'

  server:
    build: ./server
    depends_on:
      - db
    environment:
      SERVER_PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: '12345678'
      DB_NAME: shorturl
    ports:
      - "4000:4000"

  client:
    build: ./client
    ports:
      - "3000:3000"